### ISSUE TITLE
feat: add release notes analysis command

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#11]
# feat: add release notes analysis command

## Problem

Manually reviewing PRs to ensure appropriate labels for release notes categorization is time-consuming and error-prone. This often results in:
- Missing critical bug fixes in release notes
- Documentation PRs appearing in user-facing changelogs
- Inconsistent categorization across releases

**Current challenges:**
- No automated way to verify label completeness
- Manual cross-referencing of PR titles and linked issues
- Easy to miss PRs that need `ignore-for-release` label

## Proposed Solution

Add a `releases analyze` subcommand (under releases, similar to reviews/threads pattern) that analyzes PRs targeted for a release and suggests missing labels:

```bash
# Analyze release candidates
gh-helper releases analyze --milestone v0.19.0

# Analyze by date range
gh-helper releases analyze --since 2024-01-01 --until 2024-01-31

# Output suggestions in actionable format
gh-helper releases analyze --milestone v0.19.0 --format markdown
```

### Command Output Example
```yaml
releaseAnalysis:
  milestone: "v0.19.0"
  totalPRs: 15
  
  missingClassification:
    - number: 254
      title: "Fix incorrect error check"
      suggestedLabel: "bug"
      reasoning: "Fixes issue #238 which has 'bug' label"
    - number: 273
      title: "feat: expose CLI prefix"
      suggestedLabel: "enhancement"
      reasoning: "Title starts with 'feat:' prefix"
  
  shouldIgnore:
    - number: 255
      title: "Add CLAUDE.md documentation"
      suggestedLabel: "ignore-for-release"
      reasoning: "Internal development documentation only"
    - number: 291
      title: "docs: add Go coding standards"
      suggestedLabel: "ignore-for-release"
      reasoning: "Development documentation"
  
  inconsistentLabeling:
    - number: 264
      title: "Update README.md"
      currentLabels: ["documentation", "ignore-for-release"]
      issue: "Has user-facing documentation but marked as ignore"
      suggestion: "Remove 'ignore-for-release' label"
  
  summary:
    wellLabeled: 8
    needsAttention: 7
    readyForRelease: false
```

### Analysis Rules

1. **Classification Detection:**
   - Check linked issues for label inheritance
   - Parse conventional commit prefixes (feat:, fix:, docs:)
   - Analyze PR body for keywords

2. **Ignore Detection:**
   - Internal docs (CLAUDE.md, dev-docs/*)
   - CI/CD changes (.github/workflows/*)
   - Development tooling updates

3. **Consistency Checks:**
   - User-facing docs should not have `ignore-for-release`
   - Features should have either `enhancement` or `feature` label
   - Bug fixes should have `bug` label

### GraphQL Query
```graphql
query GetMilestonePRs($owner: String!, $repo: String!, $milestone: String!) {
  repository(owner: $owner, name: $repo) {
    milestone(number: $milestone) {
      pullRequests(first: 100, states: [MERGED]) {
        nodes {
          number
          title
          body
          labels(first: 10) {
            nodes { name }
          }
          closingIssuesReferences(first: 5) {
            nodes {
              number
              labels(first: 10) {
                nodes { name }
              }
            }
          }
        }
      }
    }
  }
}
```

## Acceptance Criteria

- [ ] Analyzes all PRs in a given milestone
- [ ] Suggests labels based on linked issues
- [ ] Identifies PRs that should be ignored in release notes
- [ ] Detects inconsistent labeling patterns
- [ ] Provides actionable suggestions with reasoning
- [ ] Supports multiple output formats (YAML, JSON, Markdown)
- [ ] Can analyze by date range as alternative to milestone
- [ ] Generates summary statistics for release readiness

### Pre-Release Checklist
```bash
# Check if all PRs are properly labeled
gh-helper releases analyze --milestone v0.19.0

# Generate markdown report for review
gh-helper releases analyze --milestone v0.19.0 --format markdown > release-review.md

# Apply suggestions using labels command
gh-helper releases analyze --milestone v0.19.0 --json | \
  jq -r '.missingClassification[] | "\(.number),\(.suggestedLabel)"' | \
  while IFS=, read -r pr label; do
    gh-helper labels add "$label" --items "$pr"
  done
```

### Historical Analysis
```bash
# Analyze last month's PRs
gh-helper releases analyze --since 2024-01-01 --until 2024-01-31

# Check specific PR range
gh-helper releases analyze --pr-range 250-300
```

## Future Enhancements

- Custom rule configuration via YAML file
- Release notes preview generation
- Comparison with previous releases for consistency

## Labels

- `enhancement`
- `quality`
- `release-management`
