### ISSUE TITLE
feat: add sub-issue management commands to issues subcommand

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#23]
## Overview
Add comprehensive sub-issue management commands to simplify project organization workflows that currently require complex GraphQL queries.

## Proposed Commands
- `gh-helper issues list-sub <parent>` - List all sub-issues of a parent issue
- `gh-helper issues status <parent>` - Show completion status with open/closed counts
- `gh-helper issues unlink-parent <issue>` - Remove sub-issue relationship
- `gh-helper issues move-parent <issue> --to <new-parent>` - Move sub-issue to different parent (using replaceParent: true)

## Output Format
All commands support `--format yaml|json` (default: yaml) following existing patterns.

## Example Output
```yaml
# gh-helper issues status 248
subIssueStatus:
  parent:
    number: 248
    title: "Feature: Implement caching layer"
  totalSubIssues: 20
  completedSubIssues: 15
  completionPercentage: 75
  openSubIssues:
    - number: 251
      title: "Add Redis connection pool"
    - number: 253
      title: "Implement cache invalidation"
    - number: 254
      title: "Add cache metrics"
    - number: 257
      title: "Write cache tests"
    - number: 260
      title: "Update documentation"
```

## Implementation Notes
- Extend existing `issues.go` 
- Use existing `AddSubIssue` with `replaceParent: true` for move operation
- Share GraphQL queries with existing issue operations where possible
- Follow existing YAML/JSON output patterns
