### ISSUE TITLE
feat: add thread analysis commands to threads subcommand

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#24]
## Overview
Enhance thread operations with analysis and filtering capabilities to streamline PR review workflows.

## Proposed Commands
- `gh-helper threads list <PR> [--unresolved-only] [--needs-reply]` - List threads with filtering
- `gh-helper threads stats <PR>` - Show thread statistics

## Output Format
All commands support `--format yaml|json` (default: yaml) following existing patterns.

## Example Output
```yaml
# gh-helper threads stats 312
threadStatistics:
  pullRequest:
    number: 312
    title: "Fix memory leak in connection pool"
  summary:
    total: 5
    resolved: 3
    unresolved: 2
    needsReply: 1
    outdated: 1
  byState:
    resolved:
      - id: PRRT_kwDONC6gMM5SU-GH
        path: src/cache.go
        line: 45
      - id: PRRT_kwDONC6gMM5SU-GI
        path: src/cache.go
        line: 67
      - id: PRRT_kwDONC6gMM5SU-GJ
        path: tests/cache_test.go
        line: 23
    unresolved:
      - id: PRRT_kwDONC6gMM5SU-GK
        path: src/pool.go
        line: 89
        needsReply: true
      - id: PRRT_kwDONC6gMM5SU-GL
        path: README.md
        line: 34
        isOutdated: true
```

## Implementation Notes
- Build on existing `reviews fetch --list-threads` functionality
- Reuse `ThreadFields` type from graphql_fragments.go
- Add filtering logic similar to existing `--needs-reply-only`
