### ISSUE TITLE
feat: add node-id command for GraphQL operations

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#25]
## Overview
Provide easy node ID lookups to simplify GraphQL mutation operations for AI assistants and automation.

## Proposed Commands
- `gh-helper node-id issue <number>` - Get node ID for single issue
- `gh-helper node-id pr <number>` - Get node ID for pull request  
- `gh-helper node-id --batch issue:123,pr:456,issue:789` - Batch resolution

## Output Format
All commands support `--format yaml|json` (default: yaml) following existing patterns.

## Example Output
```yaml
# gh-helper node-id issue 248
nodeId:
  type: Issue
  number: 248
  id: MDU6SXNzdWU1NjM4MjY5OTg=

# gh-helper node-id --batch issue:248,pr:312,issue:320
nodeIds:
  - type: Issue
    number: 248
    id: MDU6SXNzdWU1NjM4MjY5OTg=
  - type: PullRequest
    number: 312
    id: MDU6UHVsbFJlcXVlc3Q1NjM4MjcwMDE=
  - type: Issue
    number: 320
    id: MDU6SXNzdWU1NjM4MjcwMDI=
```

## Implementation Notes
- Use GraphQL aliases for efficient batch queries
- Follow pattern from existing `GetRepositoryID` method
- Consider internal caching for use by other commands

**Comment by apstndb** [comment]
## Additional Context

Based on the analysis of remaining GraphQL features, this command could benefit from batch operations:

### Proposed Enhancement:
```bash
# Get node IDs for multiple issues at once
gh-helper node-id issue 318 319 320

# Mix different types
gh-helper node-id mixed issue/318 pull/100 issue/320
```

### Output Format:
```yaml
items:
  - type: Issue
    number: 318
    nodeId: I_kwDONC6gMM5z1234
  - type: Issue
    number: 319
    nodeId: I_kwDONC6gMM5z1235
  - type: PullRequest
    number: 100
    nodeId: PR_kwDONC6gMM5z1236
```

This would enable efficient batch operations for other GraphQL mutations that require node IDs.
