### ISSUE TITLE
feat: add schema introspection commands for AI assistants

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#26]
## Overview
Provide schema introspection capabilities optimized for AI assistants who cannot use GraphQL Explorer.

## Proposed Commands
- `gh-helper schema type <TypeName>` - Show fields and descriptions for a type
- `gh-helper schema mutation <MutationName>` - Show mutation input requirements
- `gh-helper schema search <pattern>` - Search schema for matching types/fields

## Output Format
All commands support `--format yaml|json` (default: yaml) following existing patterns.

## Example Output
```yaml
# gh-helper schema type PullRequestReviewThread
type:
  name: PullRequestReviewThread
  description: "A thread of comments on a pull request review"
  fields:
    - name: id
      type: ID!
      description: "The unique identifier"
    - name: isResolved
      type: Boolean!
      description: "Whether this thread has been resolved"
    - name: path
      type: String
      description: "The path to the file being reviewed"
    - name: line
      type: Int
      description: "The line number being discussed"
    - name: comments
      type: PullRequestReviewCommentConnection!
      description: "The comments in this thread"
      arguments:
        - name: first
          type: Int
          description: "Number of comments to fetch"
```

## Implementation Notes
- Use GraphQL introspection queries
- Cache schema information for performance
- Format for AI consumption with clear structure
