### ISSUE TITLE
feat: add timeline command to reviews subcommand

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#27]
## Overview
Add timeline visualization for PR review history to quickly understand review progress.

## Proposed Command
- `gh-helper reviews timeline <PR>` - Show chronological review timeline

## Output Format
All commands support `--format yaml|json` (default: yaml) following existing patterns.

## Example Output
```yaml
# gh-helper reviews timeline 312
reviewTimeline:
  pullRequest:
    number: 312
    title: "Fix memory leak in connection pool"
  events:
    - timestamp: "2024-01-15T14:54:00Z"
      type: review
      actor: gemini-code-assist
      action: submitted
      state: COMMENTED
      threadCount: 3
      priority: HIGH
    - timestamp: "2024-01-15T15:36:00Z"
      type: reply
      actor: apstndb
      action: replied
      threadsResolved: 3
    - timestamp: "2024-01-15T15:39:00Z"
      type: review
      actor: gemini-code-assist
      action: submitted
      state: COMMENTED
      threadCount: 2
    - timestamp: "2024-01-15T15:44:00Z"
      type: reply
      actor: apstndb
      action: replied
      threadsResolved: 2
    - timestamp: "2024-01-15T15:46:00Z"
      type: comment
      actor: apstndb
      action: requested
      content: "/gemini summary"
    - timestamp: "2024-01-15T15:46:30Z"
      type: merge
      actor: apstndb
      action: merged
  summary:
    totalThreads: 5
    unresolvedThreads: 0
    totalReviews: 2
    totalReplies: 5
```

## Implementation Notes
- Use existing review and thread data structures
- Sort events chronologically
- Include all relevant events (reviews, replies, comments, merge)
