### ISSUE TITLE
feat: add merge readiness checker to reviews subcommand

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#28]
## Overview
Comprehensive pre-merge validation command that checks all merge requirements.

## Proposed Command
- `gh-helper reviews ready-to-merge <PR>` - Check merge readiness

## Output Format
All commands support `--format yaml|json` (default: yaml) following existing patterns.

## Example Output
```yaml
# gh-helper reviews ready-to-merge 312
mergeReadiness:
  pullRequest:
    number: 312
    title: "Fix memory leak in connection pool"
  checks:
    - name: reviewThreadsResolved
      status: pass
      message: "All review threads resolved"
    - name: ciChecksPassed
      status: pass
      message: "All CI checks passed"
    - name: requiredReviews
      status: pass
      message: "Has required reviews (1 of 1)"
    - name: geminiSummary
      status: warning
      message: "Missing /gemini summary comment"
    - name: mergeState
      status: pass
      message: "Merge state: CLEAN"
    - name: upToDate
      status: pass
      message: "Up to date with base branch"
  summary:
    readyToMerge: true
    hasWarnings: true
    recommendation: "Add /gemini summary before merging"
```

## Implementation Notes
- Build on `reviews wait --async --detailed` functionality
- Integrate PR metadata and status checks
- Provide structured output for programmatic use
