### ISSUE TITLE
feat: enhance reviews wait --async with comprehensive status data

### ISSUE THREAD

**Issue by apstndb** [apstndb/gh-dev-tools#9]
# feat: enhance reviews wait --async with comprehensive status data

## Problem

Before merging a PR, multiple conditions need to be verified manually:
- All review threads resolved
- CI checks passed
- Required reviews obtained
- No merge conflicts
- Proper review summary (e.g., /gemini summary)

Currently, `reviews wait --async` only checks for new reviews, not comprehensive PR status. This leads to:
- Premature merges with unresolved feedback
- Merges without proper review summaries
- Inconsistent merge practices across team

## Proposed Solution

Enhance the existing `reviews wait` command with two modes:

1. **Async mode with detailed status** (`--async --detailed`): Returns immediately with comprehensive data
2. **Request and wait mode** (`--request-summary`): Requests summary and waits for it

```bash
# Current behavior (reviews only)
gh-helper reviews wait 312 --async

# Enhanced: collect comprehensive status data including comments (returns immediately)
gh-helper reviews wait 312 --async --detailed

# Request Gemini summary and wait for it (mutually exclusive with --async)
gh-helper reviews wait 312 --request-summary

# Structured output for automation
gh-helper reviews wait 312 --async --detailed --json
```

### Checks Performed

1. **Review Status**
   - All review threads resolved
   - Required reviews satisfied (based on branch protection rules)
   - No requested changes blocking merge

2. **CI/CD Status**
   - All required status checks passed
   - No failing checks
   - Build/test completion

3. **Merge Status**
   - No merge conflicts
   - Mergeable state (CLEAN, HAS_HOOKS, etc.)

4. **PR Comment Analysis** (when `--detailed`)
   - Collect all PR comments with timestamps
   - Identify comment types by heading patterns:
     - **"## Summary of Changes"**: Summary comment
     - **"## Code Review"**: Review comment
   - Return structured data without interpretation:
     - List of comments with type, timestamp, and body
     - Boolean flags for analysis:
       - `hasSummaryComment`: true if any "## Summary of Changes" found
       - `hasReviewComment`: true if any "## Code Review" found
       - `lastCommentIsSummary`: true if the most recent comment is a summary

5. **Summary Request** (when `--request-summary`, mutually exclusive with `--async`)
   - Posts `/gemini summary` comment to the PR
   - Waits for Gemini to post the summary response
   - Similar to existing `--request-review` functionality

#### Example: Ready with Gemini Summary
```yaml
detailedStatus:
  pr: 312
  title: "feat: add merge readiness checker"
  
  timeline:
    prCreated: "2024-01-20T10:00:00Z"
    lastPush: "2024-01-20T10:30:00Z"
    lastReviewThreadResolved: "2024-01-20T10:35:00Z"
    
  checks:
    reviewThreads:
      status: pass
      resolved: 5
      unresolved: 0
      
    reviews:
      status: pass
      required: 1
      approved: 2
      changesRequested: 0
      
    ciStatus:
      status: pass
      required: ["build", "test", "lint"]
      passed: ["build", "test", "lint"]
      failed: []
      
    mergeability:
      status: pass
      conflicts: false
      state: "CLEAN"
      
    geminiComments:
      hasSummaryComment: true
      hasReviewComment: true
      lastCommentIsSummary: true
      comments:
        - type: "summary"
          timestamp: "2024-01-20T10:32:00Z"
          body: |
            ## Summary of Changes
            
            This PR implements a comprehensive merge readiness checker that validates multiple conditions before allowing a merge.
            
            ### Highlights
            - Added new `--merge-ready` flag to `reviews wait --async`
            - Integrated with existing review and CI check monitoring
            - Provides structured output suitable for automation
            - Includes Gemini review timing consideration
            
            The implementation follows the existing command patterns and maintains backward compatibility.
        - type: "review"
          timestamp: "2024-01-20T10:33:00Z"
          body: |
            ## Code Review
            
            The implementation looks good. All previous feedback has been addressed.
  
  # No summary or interpretation - just data
  # Users/scripts can determine readiness based on the provided data
```

#### Usage with gh pr merge
```bash
# Option 1: Request summary and wait
gh-helper reviews wait 312 --request-summary

# Then get detailed status data
STATUS_DATA=$(gh-helper reviews wait 312 --async --detailed --json)

# Extract the last summary comment for merge body
MERGE_BODY=$(echo "$STATUS_DATA" | jq -r '.geminiComments.comments[] | select(.type == "summary") | .body' | tail -1)

# Use it for squash merge
gh pr merge 312 --squash --body "$MERGE_BODY"

# Option 2: Check if summary already exists
STATUS_DATA=$(gh-helper reviews wait 312 --async --detailed --json)
if [ "$(echo $STATUS_DATA | jq -r '.geminiComments.hasSummaryComment')" = "false" ]; then
  gh-helper reviews wait 312 --request-summary
  STATUS_DATA=$(gh-helper reviews wait 312 --async --detailed --json)
fi
MERGE_BODY=$(echo "$STATUS_DATA" | jq -r '.geminiComments.comments[] | select(.type == "summary") | .body' | tail -1)
```

### Implementation Approach

1. **Extend existing async mode**:
   - Keep current behavior as default (review check only)
   - Add `--merge-ready` flag to enable comprehensive checks
   - Reuse existing GraphQL queries where possible

2. **Additional data collection**:
   - Review thread resolution status (already partially available)
   - PR comments for summary detection
   - Required reviews configuration

3. **Backward compatibility**:
   - `--async` alone continues to work as before
   - New functionality only activated with `--merge-ready`

### Exit Codes

- `0`: Ready to merge
- `1`: Not ready (blockers present)
- `2`: Ready with warnings

## Acceptance Criteria

- [ ] `--async --detailed` returns comprehensive status data immediately
- [ ] `--async` alone maintains current behavior (review check only)
- [ ] `--request-summary` posts `/gemini summary` and waits for response
- [ ] `--request-summary` and `--async` are mutually exclusive
- [ ] Checks all review threads resolution status
- [ ] Verifies required reviews are satisfied
- [ ] Validates CI/CD check status
- [ ] Detects merge conflicts
- [ ] Collects and categorizes PR comments when `--detailed`
- [ ] Provides structured data without interpretation
- [ ] Works with existing output format flags (--json, --yaml)

### Pre-Merge Validation
```bash
# Quick readiness check
gh-helper reviews wait 312 --async --merge-ready

# Enforce team practices
gh-helper reviews wait 312 --async --merge-ready --require-summary
```

### CI Integration
```bash
# In merge workflow
if gh-helper reviews wait $PR_NUMBER --async --merge-ready --quiet; then
  gh pr merge $PR_NUMBER --squash
else
  echo "PR not ready for merge"
  gh-helper reviews wait $PR_NUMBER --async --merge-ready  # Show details
  exit 1
fi
```

### Scripted Checks
```bash
# Get structured readiness data
READY=$(gh-helper reviews wait 312 --async --merge-ready --json)
if [ "$(echo $READY | jq -r '.summary.ready')" = "true" ]; then
  echo "Ready to merge!"
else
  echo "Blockers:"
  echo $READY | jq '.checks | to_entries | map(select(.value.status != "pass"))'
fi
```

### Integration with Existing Workflow
```bash
# First wait for reviews and checks
gh-helper reviews wait 312

# Then verify merge readiness
gh-helper reviews wait 312 --async --merge-ready
```

## Configuration

Support `.github/merge-requirements.yml`:
```yaml
merge_requirements:
  require_summary: true
  require_approvals: 2
  require_labels:
    - "reviewed"
    - "tested"
  require_checks:
    - "build"
    - "test"
    - "security-scan"
```

## Future Enhancements

- Integration with branch protection rules
- Custom check plugins
- Historical compliance reporting
- Auto-fix for common issues (e.g., request summary)
- Integration with release readiness

## Labels

- `enhancement`
- `quality`
- `automation`
- `developer-experience`
